### PR TITLE
Update documentation of the database feature (#31)

### PR DESCRIPTION
**Pull request by itays123**
I hope I covered all topics

### CODE REVIEW

**Comment by itays123** [comment]
I also changed the process.ts file since it messed up the entire application.ts file. 
now the code is way clearer and better in my opinion, but if it feels weird to you it's okay. tell me what you think.

**Comment by aaronwlee** [comment]
Looks cool but all kinds of middleware types must inherit the generic DB.
and Response should inherit the generic DB and Request should have got a secure parameter.

```ts
  middlewares: MiddlewareProps<DB>[],
  errorMiddlewares: ErrorMiddlewareProps<DB>[],

  const res = new Response<DB>(srq);
  const req = new Request(srq, secure);
```

can you fix these things?

**Comment by itays123** [comment]
Yes I can. On it

**Comment by aaronwlee** [comment]
I'll release this feature as a 1.1.0 version this Thursday right after Deno version up to 1.3.0. :)

**Pull request merged**
